artifact_uri: file:///home/mle-user/mle_projects/mle-mlflow/mlflow_experiments_store/0/8898b86039b84c718a6d17c5fa7ed699/artifacts
end_time: 1721542898541
entry_point_name: ''
experiment_id: '0'
lifecycle_stage: active
run_id: 8898b86039b84c718a6d17c5fa7ed699
run_name: Default
run_uuid: 8898b86039b84c718a6d17c5fa7ed699
source_name: ''
source_type: 4
source_version: ''
start_time: 1721542898531
status: 4
tags: []
user_id: mle-user
